// 02 React Translate/src/App.tsx
import React from "react";
import axios from "axios";

import i18next from "i18next";

type State = {
  tekst: string;
};
class App extends React.Component {
  state: State = {tekst: ""};
  lang: string = "en";

  componentDidMount = async () => {
    await i18next.changeLanguage(this.lang);
    const config: string | any = axios.defaults.headers;
    config["Accept-Language"] = this.lang;
    // console.log(config["Accept-Language"]);
    const response = await axios.get("http://localhost:8000/text");
    const temp1 = response.data;
    const temp2 = temp1["text"];
    // console.log(temp2);
    this.setState({tekst: temp2});
    // console.log(this.state);
  };

  change = async (lang: string) => {
    this.lang = lang;
    await this.componentDidMount();
  };

  click = async () => {
    const response = await axios.post("http://localhost:8000/like");
    // console.log(response);                      // -Odpowiedź z serwera
    const temp1 = response.data["message"];
    if (!temp1) {
      console.log("waiting");
    }
    // console.log(temp1);
    const text: string = i18next.t("thank_you");
    // console.log(text);                          // -Odpowiedź z aplikacji
    alert(text);
  };

  render() {
    return (
      <main className="container">
        <div className="row py-3">
          <div className="col-10"></div>
          <div className="col-2">
            <select className="form-control" onChange={(e) => this.change(e.target.value)}>
              <option value="en">English</option>
              <option value="pl">Polish</option>
            </select>
          </div>
        </div>
        <div className="row">
          <div className="col-md12">
            {/* <h2>This text is translated in the frontend:</h2> */}
            <h2>{i18next.t("title")}</h2>
            {/* <p>This is translated in the backend:</p> */}
            <p>{this.state.tekst}</p>
            <button className="btn btn-outline-primary" onClick={this.click}>
              {i18next.t("like")}
            </button>
          </div>
        </div>
      </main>
    );
  }
}

export default App;

// 04 Vue Translate/src/App.vue
<template>
  <main class="container">
    <div class="row py-3">
      <div class="col-10"></div>
      <div class="col-2">
        <select class="form-control" @change="change($event.target.value)">
          <option value="en">English</option>
          <option value="pl">Polish</option>
        </select>
      </div>
    </div>
    <div class="row">
      <div class="col-md12">
        <h2>{{ t("title", {}, {locale: lang}) }}</h2>
        <p>{{ text }}</p>
        <button class="btn btn-outline-primary" @click="click()">{{ t("like", {}, {locale: lang}) }}</button>
      </div>
    </div>
  </main>
</template>

<script lang="ts">
import {defineComponent} from "vue";
import axios from "axios";
import {useI18n} from "vue-i18n";

export default defineComponent({
  name: "App",
  setup() {
    const {t, locale} = useI18n();
    return {t, locale};
  },
  data() {
    return {
      text: "",
      lang: "en",
    };
  },
  async mounted() {
    await this.load();
  },
  methods: {
    async load() {
      // axios.defaults.headers["Accept-Language"] = this.lang;
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const config: string | any = axios.defaults.headers;
      config["Accept-Language"] = this.lang;
      const response = await axios.get("http://localhost:8000/text");
      this.text = response.data["text"];
    },

    async change(lang: string) {
      this.lang = lang;
      this.load();
    },
    async click() {
      const response = await axios.post("http://localhost:8000/like");
      const temp = response.data["message"];
      if (!temp) {
        console.log("waiting");
      }

      const text: string = this.t("thank_you", {}, {locale: this.lang});
      alert(text);
    },
  },
});
</script>
